language: node_js

node_js:
  - "stable"
script: test.sh
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

env:
  matrix:
  - COMMAND=test
  - COVERAGE=1 REPORT_COVERAGE=1 COMMAND=test

branches:
  only:
  - master
  - /^pull*$/

matrix:
  include:
    - node_js: "0.12"
      env: COMMAND=test
    - node_js: "4.0.0"
      env: COMMAND=test